### ISSUE TITLE
How do I configure font sizes of markups?

### ISSUE THREAD

**Issue by pismute** [sensorflo/adoc-mode#11]
Hi. adoc-mode is amazing.

How do I configure font sizes of markups?
I am new for asciidoc so that I want to see markups like `===`, `[]`.

 Thank you.

**Comment by sensorflo** [comment]
You can do that in the customization group markup-faces:
- M-x customize-group RET markup-faces RET
- Descent into 'Markup Faces Meta'

Just in case you don't know Emacs' customization:
- Display the Emacs manual in Info mode with "C-h r" or "M-x info-emacs-manual"
- Descent into menu "Customization"

Cheers

**Comment by pismute** [comment]
Thank you a lot.

**Comment by sensorflo** [comment]
I also pushed a new commit.  The doc comment of the adoc customization group now describes more clearly that most faces used belong to the markup-faces customization group and have to be customized there.
