### ISSUE TITLE
Error while compiling from elpa

### ISSUE THREAD

**Issue by PierreR** [sensorflo/adoc-mode#12]
I am probably missing something ?
```
Compiling file /home/.emacs.d/elpa/adoc-mode-20150102.835/adoc-mode.el at Mon Mar  2 23:38:14 2015
adoc-mode.el:178:1:Warning: cl package required at runtime
adoc-mode.el:1688:1:Error: Symbol's function definition is void: adoc-re-verbatim-paragraph-sequence
```
I am using GNU Emacs 24.4.1

Cheers

**Comment by kwhitefoot** [comment]
I have the same problem.  have you found a work around?

**Comment by kwhitefoot** [comment]
Rats. Github won't let me edit my comment. 

Forgot to say I'm using Emacs 24.3.1 on Lubuntu 14.04.2 LTS.

**Comment by sensorflo** [comment]
Thank you for the hint. I just pushed the bugfix
