### ISSUE TITLE
Fonts not correctly displayed

### ISSUE THREAD

**Issue by Enrico68** [sensorflo/adoc-mode#13]
I don't know if it is a normal behaviour but some fonts looks to small for me:

![screenshot](http://i.imgur.com/D3cRxril.jpg) 

Links, quoted text, comments are all displayed with tiny fonts.

**Comment by hijarian** [comment]
This is intended behavior.

**Comment by sensorflo** [comment]
hijarian is right, this is how the faces by default look like. You can customize them via
`M-x customize-group markup-faces RET`

**Comment by hijarian** [comment]
@sensorflo Holy cow, they can be customized via `customize` facility? 0_o' Awesome!

**Comment by Enrico68** [comment]
Saphronov Mark <notifications@github.com> writes:

> @sensorflo Holy cow, they can be customized via `customize` facility? 0_o' Awesome!

Great! thanks for this awesome mode.... 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sensorflo/adoc-mode/issues/13#issuecomment-105037319

-- 
Dr. Enrico Pirani
Medico Chirurgo
Specialista in Chirurgia Toracica
FMH Chirurgia Cardiaca 
Via Matteotti 7
35042 Este (Padova)

Cell:392-6224668
Tel: 0429-17660135

  Ai sensi del D.Lgs. 196/2003 si precisa che le informazioni contenute in
  questo messaggio sono riservate ed a uso esclusivo del destinatario.
  Qualora il messaggio Le fosse pervenuto per errore, La invitiamo ad
  eliminarlo senza copiarlo e a non inoltrarlo a terzi, dandocene gentilmente
  comunicazione. Grazie.

  Pursuant to Legislative Decree No. 196/2003, you are hereby informed that
  this message contains confidential information intended only for the use of
  the addressee. If you are not the addressee, and have received this message
  by mistake, please delete it and immediately notify us. You may not copy or

**Comment by sensorflo** [comment]
Note that adoc-mode related things can also be customized:
`M-x customize-group adoc RET`
