### ISSUE TITLE
Long footnotes not recognised

### ISSUE THREAD

**Issue by Quintus** [sensorflo/adoc-mode#17]
The highlighter doesn’t properly recognise long footnotes, even if they do not include multiple paragraphs. Excerpt from my document:

~~~~~~~~~~~~~~~~
Dies nennt man die Methodenfootnote:[Passive
Fähigkeiten sind in der Objektorientierung ein Zeichen schlechten
Stils. Eine Methode »hochgehoben werden« würde als unpassend angesehen
werden.]. Im Gegensatz dazu zeugen die Attribute bloß vom
Zustand eines Objekts.
~~~~~~~~~~~~~~~~

That there’s no space between the word "Methoden" and the "footnote:" macro is intentional. This is legal ASCIIDoc input and suppresses the annoying space between word and footnote. The highlighting still doesn’t work if one puts the space in, though.

Greetings
Marvin

**Comment by sensorflo** [comment]
I just pushed 0.6.5. It fixes these bugs you reported and a bit more
- the inline macros footnote and footnoteref can now be placed hard up against the preceding word
- inline and block macros (which includes footnote and footnoteref) and (un)constrained quotes now can spawn multiple lines
