### ISSUE TITLE
adoc-mode with colouring only, not fontlock

### ISSUE THREAD

**Issue by homberghp** [sensorflo/adoc-mode#20]
It the gist of asciidoc and asciidoctor I would prefer less distraction while writing. For me
changed (enlarged, other) fonts are distracting, in particular font-size.

I would welcome a variant or a switch which would allow me to turn off font locking.

**Comment by sensorflo** [comment]
Is customizing the faces what you are searching for? Like so `M-x customize-group RET markup-faces`.

**Comment by homberghp** [comment]
probably,  thx
Op 6 mrt. 2016 17:45 schreef "Florian Kaufmann" <notifications@github.com>:
