### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by KantarBruceAdams** [sensorflo/adoc-mode#34]
when I run M-x adoc-mode I get:

   Symbol's value as variable is void: <!DOCTYPE

This is on RHEL7 running:

 GNU Emacs 24.3.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.10)

There is no mention of DOCTYPE in the mode file itself. Its not immediately obvious what went wrong or where to start debugging this.

**Comment by tiensonqin** [comment]
@KantarBruceAdams I encountered this problem too.

The reason is that adoc-mode depends on markup-faces, 
If you check your markup-faces.el, it's an html file, not elisp.
Replace it with the right file works for me!

**Comment by tiensonqin** [comment]
I also write a blog post: 
https://hidifferent.com/@tiensonqin/emacs-adoc-mode-installation-error-2xyhw0w5vw

**Comment by KantarBruceAdams** [comment]
Thanks. That fixed it.  I studied the adoc-mode but not the extension it depended on.
