### ISSUE TITLE
broken syntax [,] causes emacs to hang

### ISSUE THREAD

**Issue by jdukes** [sensorflo/adoc-mode#9]
The string `[,]` appears to cause adoc-mode to hang. The syntax `[source,lang]` is used to allow syntax highlighting of code blocks. Another user may incorrectly leave out the `lang`. If this happens adoc-mode will hang indefinitely parsing the file. 

adoc-mode version: 20130917.0

Reproduction steps:
1. create an ascii-doc document or switch to adoc mode in an existing buffer.
2. type the characters `[,]`

Observed behavior: 
Emacs hangs. This is sometimes recoverable by repeatedly hitting `C-g` and backspace to delete the string.

**Comment by twlz0ne** [comment]
Same issue.

- **emacs** 24.5.1
- **adoc-mode**  20151119.914

**Comment by fidergo-stephane-gourichon** [comment]
@twlz0ne Can you try version from branch `fix/non-termination-on-zero-width-attribute` ? It fixed for me. https://github.com/phillord/adoc-mode/commit/767596ecf01a6843bd2d5410e3a3cfde8f0d8170 https://github.com/phillord/adoc-mode/tree/fix/non-termination-on-zero-width-attribute

**Comment by twlz0ne** [comment]
@fidergo-stephane-gourichon, it worked, thanks for you reminder.

Is there any way to reopen this issue? Hope @sensorflo notice that, commit e6b8e69 does not fix the problem(at least for me).

**Comment by fidergo-stephane-gourichon** [comment]
@twlz0ne, it is now clear that current master should not exhibit that bug. Perhaps the version you were using contained neither commit discussed on https://github.com/sensorflo/adoc-mode/pull/21 ? Personally, I switched from 767596e to sensorflo/master and am happy with it. Keeping issue closed.
